@extends('front.layout')

@section('content')
<div class="container_flex_white">
    <article>
        <h2>VŠEOBECNÉ OBCHODNÉ PODMIENKY</h2>
        <p>
            Tieto všeobecné obchodné podmienky (ďalej len „VOP“) sa vzťahujú na vzťahy, ktoré vznikli registráciou na portáli www.vymozete.sk a/alebo na Príkazné zmluvy uzavreté medzi spoločnosťou iVymáhanie s.r.o., so sídlom Zámocká 30, 811 01 Bratislava – mestská časť Staré Mesto, IČO: 51 025 876, zapísaná v Obchodnom registri Okresného súdu Bratislava I, oddiel: Sro, vložka č. 123274/B (ďalej len „Príkazník“) a advokátskou kanceláriou BARKOCI law firm, s.r.o., so sídlom Námestie slobody 28, 811 06 Bratislava -Staré Mesto, IČO: 47 247 916, zapísaná v Obchodnom registri Okresného súdu Bratislava I, oddiel: Sro, vložka č. 88740/B (ďalej len „Advokát“) a  Príkazcom (Príkazcom sa na účely týchto VOP rozumie fyzická alebo právnická osoba, ktorá sa registrovala na portáli www.vymozete.sk a/alebo uzavrela Príkaznú zmluvu s Príkazníkom a Advokátom).
        </p>
        <br>
        <h2>1. ÚVODNÉ USTANOVENIA</h2>
        <p>
            1.1.	Príkaznou zmluvou sa Príkazník zaväzuje v mene Príkazcu a na jeho účet robiť úkony smerujúce k vymoženiu pohľadávky bližšie špecifikovanej v Príkaznej zmluve (ďalej len „Príkazná zmluva“), vrátane jej príslušenstva a prípadných zmluvných sankcií (ďalej len „Pohľadávka“) od dlžníka Príkazcu a Príkazca sa zaväzuje uhradiť Príkazníkovi a Advokátovi za činnosť, ktorá je predmetomPríkaznej zmluvy odmenu vo výške dohodnutej v Príkaznej zmluve.
            <br><br>1.2.	Advokát sa zaväzuje poskytnúť Príkazcovi právne služby spočívajúce v zastupovaní Príkazcu pri uplatňovaní jeho nároku, predmetom, ktorého je zaplatenie Pohľadávky a jej príslušenstva, a to až do jej úplného zaplatenia, vrátane uplatnenia nároku v súdnom aj exekučnom konaní, pričom právne služby sa Advokát zaväzuje poskytnúť podľa zákona č. 586/2003 Z. z. o advokácii v znení neskorších predpisov, ktoré sú bližšie špecifikované v bode 1.3 tohto článku VOP, a to všetko za predpokladu poskytnutia všetkej Advokátom požadovanej súčinnosti zo strany Príkazcu.
            <br><br>1.3.	Právne služby zahŕňajú najmä rokovanie s označenými partnermi, rokovanie s dlžníkomPríkazcu, zastupovanie v konaniach na súdoch, iných štátnych a miestnych orgánoch, spisovanie podaní, návrhov, opravných prostriedkov, žiadostí, podávanie prihlášok do konkurzov a reštrukturalizácií, spracovanie právnych rozborov,  poskytovanie odborných právnych rád a správa Pohľadávky Príkazcu v zmysle jeho pokynov. Advokát je povinný chrániť práva a oprávnené záujmy Príkazcu, konať pritom svedomito, dôsledne využívať všetky zákonné prostriedky a uplatňovať, čo podľa svojho presvedčenia a príkazu Príkazcu pokladá za prospešné. Advokát sa zaväzuje poskytovať právne služby účelne a hospodárne pri využití všetkých zákonných prostriedkov v rámci príkazu Príkazcu.Príkazca je povinný poskytnúť Advokátovi všetku ním požadovanú a nevyhnutnú súčinnosť pri poskytovaní právnych služieb vo veci vymáhania Pohľadávky. Advokát nenesie zodpovednosť za poskytnuté služby a škodu, v prípade, že Príkazca odmietol Advokátovi poskytnúť požadovanú a nevyhnutnú súčinnosť pri vymáhaní Pohľadávky.
            <br><br>1.4.	Príkazca udeľuje Príkazníkovi a / alebo Advokátovi výslovný súhlas na to, aby Príkazník a/alebo Advokát v mene Príkazcu vyjednával a uzatváral splátkové kalendáre, predmetom ktorých je úhrada Pohľadávky a rokoval o podmienkach finančného urovnania medzi Príkazcom a jeho dlžníkom.
            <br><br>1.5.	Príkazca berie výslovne na vedomie a súhlasí s tým, že na základe Príkaznej zmluvy nie je Príkazník a / alebo Advokát v priebehu trvania Príkaznej zmluvy povinný vykonávať kontrolu, či proti dlžníkovi Príkazcu bolo začaté alebo či prebieha konkurzné konanie alebo reštrukturalizačné konanie, alebo ak sa jedná o dlžníka fyzickú osobu oddlženie konkurzom alebo splátkovým kalendárom, a Príkazník a/alebo Advokát nenesie teda právnu zodpovednosť za škodu spôsobenú v dôsledku zmeškania prihlásenia vymáhanej Pohľadávky do konkurzného konania, reštrukturalizačného konania alebo v rámci oddlženia, nakoľko uvedené nie je predmetom Príkaznej zmluvy.Príkazca si je vedomý, že kontrolu, či proti dlžníkovi bolo začaté alebo či prebieha konkurzné konanie alebo reštrukturalizačné konanie, alebo ak sa jedná o dlžníka fyzickú osobu oddlženie konkurzom alebo splátkovým kalendárom, je povinný vykonávať sám.
            <br><br>1.6.	Advokáta môže pri jednotlivých úkonoch právnej služby zastúpiť advokátsky koncipient alebo iný pracovník Advokáta.Advokát sa v rámci svojho poverenia môže dať zastúpiť iným advokátom. Takéto zastupovanie však nie je možné proti vôli Príkazcu; svoj nesúhlas musí Príkazca preukázať Advokátovi písomne a nesúhlas so zastupovaním je účinný voči Advokátovi až odo dňa písomného doručenia nesúhlasu Príkazcu.
            <br><br>1.7.	Práva a povinnosti Príkazníka a Advokáta podľa Príkaznej zmluvy sú koncipované samostatne, a teda nie ako spoločné práva a spoločné záväzky.
        </p>
        <br>
        <h2>2. SPOTREBITELIA</h2>
        <p>2.1.	O spotrebiteľskú zmluvu sa jedná v prípade, že Príkazca je spotrebiteľom, to znamená fyzickou osobou, ktorá siobjednáva služby v zmysle Príkaznej zmluvy mimo rámec svojej podnikateľskej činnosti alebo mimo rámec samostatného výkonu svojho povolania. V opačnom prípade sa o spotrebiteľskú zmluvu nejedná a nevzťahuje sa naPríkazcu ochrana spotrebiteľa podľa právnych predpisov (najmä § 52 a nasl. zákona č. 40/1964 Zb. Občiansky zákonník v znení neskorších predpisov, zákon č.     250/2007 Z.z. o ochrane spotrebiteľa v znení neskorších predpisov, zákon č. 102/2014 Z.z. o ochrane spotrebiteľa pri predaji tovaru alebo poskytovaní služieb na základe zmluvy uzavretej na diaľku alebo zmluvy uzavretej mimo prevádzkových priestorov predávajúceho a o zmene a doplnení niektorých zákonov v znení neskorších predpisov) a týchto VOP.
            <br><br>2.2.	Príkazník a Advokát oboznamujú Príkazcu, ktorý je spotrebiteľom v súvislosti s Príkaznou zmluvou uzatvorenou na diaľku alebo mimo prevádzkových priestorov Príkazníka a/alebo Advokáta o nasledovnom:
            <br><br>2.2.1.	Náklady na prostriedky komunikácie na diaľku, ktoré Príkazcovi vznikli v súvislosti s uzatvorením a plnením Príkaznej zmluvy a prijatím služby, sú jeho vlastnými nákladmi a nesie si ich sám. V praxi sú tieto náklady predstavované poštovným v súvislosti s odoslaním podpísanej Príkaznej zmluvy Príkazníkovi a Advokátovi.
            <br><br>2.2.2.	V procese plnenia Príkaznej zmluvy, teda vymáhania Pohľadávky, bude v prípade súdneho vymáhania Pohľadávky nutné uhradiť súdny poplatok vo výške podľa platných právnych predpisov. Ďalej nemožno vylúčiť, že v rámci súdneho vymáhania Pohľadávky súd uloží Príkazcovi akožalobcovi povinnosť uhradiť preddavok na vykonanie dôkazu, najmä znaleckého posudku.
            <br><br>2.2.3.	Príkazca je oprávnený reklamovať vady služieb vykonávaných Príkazníkom a/alebo Advokátom v zmysle Príkaznej zmluvy v lehote 10 dní odo dňa výskytu príslušnej vady, a to prostredníctvom e-mailu na adrese office@vymozete.sk. V reklamácii je Príkazca povinný presne špecifikovať v čom spočíva reklamovaná vada. Príkazník a/alebo Advokát je povinný doručiť Príkazcovi potvrdenie o uplatnení reklamácie prostredníctvom e-mailu. Ak nie je možné potvrdenie doručiť ihneď, musí sa doručiť bez zbytočného odkladu, najneskôr však spolu s dokladom o vybavení reklamácie. V prípade, ak sa preukáže, že reklamácia je opodstatnená, Príkazník a/alebo Advokát je povinný reklamovanú vadu odstrániť. O vybavení reklamácie je Príkazník a/alebo Advokát povinný informovaťPríkazcu.
            <br><br>2.2.4.	Práva Príkazcu z vadného plnenia sa riadia  príslušnými všeobecne záväznými právnymi predpismi platnými na území Slovenskej republiky.
            <br><br>2.2.5.	Vo vzťahu k Príkazcovi Príkazník a/alebo Advokát nie je viazaný žiadnymi kódexami správania.
            <br><br>2.2.6.	Od Príkaznej zmluvy uzavretej na diaľku alebo uzavretej mimo prevádzkových priestorov Príkazníka a/alebo Advokáta má Príkazca právo odstúpiť bez udania dôvodu, a to do 14 dní od jej uzavretia. Právo na odstúpenie od Príkaznej zmluvy uplatní Príkazca tak, že odstúpenie od zmluvy zašle písomne na adresu iVymáhanie s.r.o., so sídlom Zámocká 34, 811 01 Bratislava. Na odstúpenie od Príkaznej zmluvy možno použiť formulár na odstúpenie uvedený v bode 2.3. týchto VOP. Pre dodržanie lehoty je nutné, aby poštová zásielka s písomným odstúpením bola odoslaná najneskôr v posledný deň 14-dňovej lehoty na odstúpenie. AkPríkazca odstúpi od Príkaznej zmluvy v 14-dňovej lehote, Príkazník a/alebo Advokátvráti Príkazcovi bez zbytočného odkladu všetky platby, ktoré prípadne od Príkazcu dostali; toto však neplatí, ak bol Príkazník a/alebo Advokát výslovne Príkazcom požiadaný, aby s vymáhaním Pohľadávky začali pred uplynutím 14-dňovej lehoty na odstúpenie. V takom prípade má Advokát nárok na úhradu odmeny za dovtedy vykonané úkony právnej služby vo výške podľa vyhlášky MS SR č. 655/2004 Z. z. v platnom znení.
            <br><br>2.2.7.	Alternatívne riešenie sporov z Príkaznej zmluvy je možné prostredníctvom subjektu alternatívneho riešenia sporov; Subjektom alternatívneho riešenia sporov je orgán alternatívneho riešenia sporov alebo právnická osoba zapísaná v zozname podľa § 5 ods. 2 zákona č. 391/2015 Z .z. Riešenie sporov uvedeným spôsobom je založené na dobrovoľnej účasti obidvoch strán, objektivite a nestrannosti konania; subjektom alternatívneho riešenia sporov vo vzťahu k Príkazníkovi je Slovenská obchodná inšpekcia. Odkaz na platformu alternatívneho riešenia sporov prostredníctvom ktorej môže Príkazca podať návrh na začatie alternatívneho riešenia sporu je:  https://www.soi.sk/sk/Alternativne-riesenie-spotrebitelskych-sporov.soi , ktorý je súčasne uvedený aj na webovom sídle Príkazníka).
            <br><br>2.2.8.	Ďalšie informácie, ktoré majú byť spotrebiteľovi v zmysle § 3 ods. 1 zákona č. 102/2014 Z.z. o ochrane spotrebiteľa pri predaji tovaru alebo poskytovaní služieb na základe zmluvy uzavretej na diaľku alebo zmluvy uzavretej mimo prevádzkových priestorov predávajúceho a o zmene a doplnení niektorých zákonov oznámené pred uzavretím Príkaznej zmluvy sú obsiahnuté v ostatných ustanoveniach Príkaznej zmluvy a týchto VOP.
            <br><br>2.3.	Vzorový formulár pre odstúpenie od zmluvy:
        </p>
        <p><strong>Adresát:</strong>
            <br>iVymáhanie s.r.o., Zámocká 30, 811 01 Bratislava</p>
        <p><strong>Text odstúpenia:</strong>
            <br>Týmto oznamujem, že týmto odstupujem od Príkaznej zmluvy mnou podpísanej dňa [doplniť]</p>
        <p><strong>Vaše meno a priezvisko:</strong>
            <br>[doplniť]</p>
        <p><strong>Vaša adresa:</strong><br>[doplniť]</p>
        <p><strong>Dátum:</strong><br>[doplniť]</p>
        <p><strong>Váš podpis:</strong><br>(iba ak je odstúpenie uskutočňované v listinnej podobe)</p>
        <br>
        <h2>3. SPÔSOB UZAVRETIA PRÍKAZNEJ ZMLUVY</h2>
        <p>3.1.	Pred uzavretím Príkaznej zmluvy je Príkazca povinný vykonať bezplatnú registráciu cez webové rozhraniePríkazníka na www.vymozete.sk. Po vykonaní registrácii Príkazca vyplní formulár, ktorý obsahuje najmäidentifikačné údaje Príkazcu, údaje o Pohľadávke a identifikačné údaje dlžníka. Takto vyplnený formulár odošle Príkazca prostredníctvom webového rozhraniawww.vymozete.skPríkazníkovi.
            <br><br>3.2.	Po prijatí vyplneného formulára v zmysle bodu 3.1. týchto VOP Príkazník následne vykoná bezplatnú lustráciu dlžníka Príkazcu. Výsledkom lustrácie môže byť záver, že dlžník Príkazcu nie je bonitný alebo je bonitný.
            <br><br>3.3.	V prípade, že výsledkom lustrácie dlžníka Príkazcu v zmysle bodu 3.2. týchto VOP bude záver, že dlžník Príkazcu nie je bonitný, Príkazník zašle Príkazcovi správu (sms alebo e-mail) o tom, že dlžník Príkazcu nie je bonitný a že Príkazník v tomto prípade z dôvodu potenciálnej nevymožiteľnosti Pohľadávky neprevezme vymáhanie Pohľadávky.
            <br><br>3.4.	V prípade, že výsledkom lustrácie dlžníka Príkazcu v zmysle bodu 3.2. týchto VOP bude záver, že dlžník Príkazcu je bonitný, Príkazník zašle Príkazcovi písomný návrh na uzavretie Príkaznej zmluvy spolu s príslušnými prílohami.
            <br><br>3.5.	V prípade, že výsledkom lustrácie dlžníka Príkazcu bude záver, že dlžník je bonitný, Príkazník môže prejaviť záujem o Pohľadávku a Príkazcovi predložiť ponuku na odpredaj Pohľadávky (návrh na uzavretie zmluvy o postúpení Pohľadávky).
            <br><br>3.6.	Príkazná zmluva sa považuje za riadne uzavretú dňom jej podpísania všetkými zmluvnými stranami a doručením 1 (jedného) vyhotovenia riadne podpísanej zmluvy Príkazníkovi a Advokátovi zo strany Príkazcu. Príkazník a/alebo Advokát nie je povinný začať poskytovať služby v zmysle Príkaznej zmluvy pred okamihom doručenia riadne podpísanej Príkaznej zmluvy Príkazcom Príkazníkovi a/alebo Advokátovi.
            <br><br>3.7.	Zaslaním vyplneného formulára v zmysle bodu 3.1. týchto VOP a potvrdením vo webovom rozhraníwww.vymozete.skPríkazca potvrdzuje, že sa oboznámil s týmito VOP a súhlasí s nimi.
        </p>
        <br>
        <h2>4. PLATOBNÉ PODMIENKY</h2>
        <p>4.1.	Výška odmeny Príkazníka a Advokáta je stanovená v Príkaznej zmluve.
            <br><br>4.2.	Príkazníkovi vzniká nárok na odmenu až momentom vymoženia Pohľadávky alebo jej časti. Odmena Príkazníka za obstaranie záležitosti je stanovená percentuálnym podielom z vymoženej Pohľadávky alebo jej časti plus daň z pridanej hodnoty, účtovaná v zmysle platných predpisov. Príkazca berie na vedomie, že od okamihu uzavretia Príkaznej zmluvy sa akékoľvek platby Dlžníka považujú za vymožené na základePríkaznej zmluvy.
            <br><br>4.3.	Príkazca výslovne splnomocňuje Príkazníka, aby inkasoval platby od Dlžníka na vymáhanú Pohľadávku. Trovy právneho zastúpenia inkasuje Advokát. Po vymožení Pohľadávky alebo jej časti, je Príkazník povinný ju Príkazcovi bez zbytočného odkladu vyúčtovať po odčítaní odmeny Príkazníka podľa bodu 4.2 VOP.
            <br><br> 4.4.	Ak je Pohľadávka, alebo jej časť uhradená Dlžníkom priamo Príkazcovi, Príkazca je povinný o tom bezodkladne informovať Príkazníka a zároveň je Príkazca povinný uhradiť Príkazníkovi odmenu podľa bodu 4.2VOP do piatich (5) pracovných dní odo dňa obdržania úhrady.
            <br><br>4.5.	Zmluvné strany sa dohodli, že Príkazca je povinný v prípade zmarenia účelu Príkaznej zmluvy a/alebo porušenia povinností podľa Príkaznej zmluvy zo strany Príkazcu uhradiť Advokátovi tarifnú odmenu za vykonané úkony právnej služby, náhradu hotových výdavkov náhradu za stratu času a náhradu výdavkov na miestne telekomunikačné výdavky a miestne prepravné sumu vo výške jednej stotiny výpočtového základu za každý úkon právnej služby (režijný paušál)v zmysle  vyhlášky Ministerstva spravodlivosti Slovenskej republiky č. 655/2004 Z. z., o odmenách a náhradách advokátov za poskytovanie právnych služieb. Príkazca je povinný v prípade zmarenia účelu Príkaznej zmluvy uhradiť Príkazníkovi zmluvnú pokutu vo výške 10% z Pohľadávky. Zmarením účelu Príkaznej zmluvy sa pre účely Príkaznej zmluvy rozumie:
            <br><br>4.5.1.	neuhradenie súdneho poplatku, preddavku na vykonanie dôkazov, znalecký posudok či nákladov mediácie Príkazcom, alebo
            <br><br>4.5.2.	neúčasť Príkazcu na súdom nariadenej mediácii po písomnej výzve Advokáta, alebo
            <br><br>4.5.3.	ak vyjde najavo v súdnom alebo inom konaní, že Pohľadávka neexistuje, alebo
            <br><br>4.5.4.	porušenie povinnosti informovať o akýchkoľvek platbách Príkazcovi poskytnutých na vymáhanú Pohľadávku, vrátane akýchkoľvek zápočtov na ňu, alebo
            <br><br>4.5.5.	porušenie povinností Príkazcu v zmysle Príkaznej zmluvy.
            <br><br>4.6.	Príkazca je povinný v prípade svojho rozhodnutia nepokračovať vo vymáhaní Pohľadávky na základe Príkaznej zmluvy, vrátane rozhodnutia nepokračovať vo vymáhaní Pohľadávky v exekučnom konaní po vydaní právoplatného rozhodnutia uhradiť  Príkazníkovi paušálnu náhradu výdavkov vo výške  vo výške 20% z Pohľadávky.
            <br><br>4.7.	Príkazca a Príkazník sa dohodli, že odmenu Advokáta bude znášať Príkazca až dňom vymoženia Pohľadávky alebo jej časti; do tohto momentu znáša odmenu Advokáta v celom rozsahu Príkazník. Po vymožení Pohľadávky alebo jej časti sa Príkazca zaväzuje zaplatiť Advokátovi odmenu (v prípade vymoženia časti Pohľadávky jej pomernú časť), ktorá bola dohodnutá ako tarifná odmena v zmysle ustanovenia § 10 a nasl. vyhlášky Ministerstva spravodlivosti SR č. 655/2004 Z.z. o odmenách a náhradách advokátov za poskytovanie právnych služieb (ďalej len „tarifná odmena“). K tarifnej odmene sa pripočítava náhrada výdavkov na miestne telekomunikačné výdavky a miestne prepravné sumu vo výške jednej stotiny výpočtového základu za každý úkon právnej služby (režijný paušál), ktorý bude Príkazcovi účtovaný v súlade s právnymi predpismi platnými v čase, kedy je úkon právnej služby vykonaný. Odmena Advokáta je vypočítaná ako násobok počtu Advokátom vykonaných úkonov právnej služby a tarifnej odmeny spolu s režijným paušálom (ďalej len „odmena Advokáta“). K odmene Advokáta sa pripočítava príslušná sadzba dane z pridanej hodnoty podľa aktuálnej právnej úpravy. Ustanovenie § 13a vyhlášky sa aplikuje analogicky.
            <br><br>4.8.	Príkazca potvrdzuje, že bol Advokátom pred začatím poskytovania právnych služieb informovaný o výške tarifnej odmeny za úkon právnej služby a poučený o spôsobe výpočtu odmeny Advokáta a tomuto spôsobu výpočtu porozumel a súhlasí s ním, čo potvrdzuje udelením súhlasu s týmito VOP. Príkazca zároveň potvrdzuje, že bol zároveň oboznámený o potrebe všetkých predpokladaných úkonov právnej služby, ktoré bude musieť Advokát v budúcnosti vykonať v právnej veci vymáhania Pohľadávky.
            <br><br>4.9.	Advokát zároveň poučuje Príkazcu, že v prípade neúspešného ukončenia právnej veci je Príkazca povinný zaplatiť náhradu trov konania, zahŕňajúcu aj prípadné trovy právneho zastúpenia, účastníkovi, ktorý vo veci úspech mal.
        </p>
        <br>
        <h2>5. PRÁVA A POVINNOSTI PRÍKAZCU</h2>
        <p>5.1.	Príkazca je povinný poskytnúť Príkazníkovi a Advokátovi o Pohľadávke a dlžníkovi všetky jemu známe a existujúce informácie, údaje a doklady, ktoré majú súvislosť s plnením predmetu Príkaznej zmluvy, a zadávať Príkazníkovi a/alebo Advokátovi pokyny zrozumiteľne a jednoznačne. Príkazca je ďalej povinný poskytnúťPríkazníkovi a/alebo Advokátovi súčinnosť potrebnú k naplneniu účelu Príkaznej zmluvy, najmä aktualizovať svoje kontaktné údaje a udržiavať komunikáciu v lehotách obvyklých pre zvolený spôsob komunikácie (e-mail, telefón), t.j. do 2 (dvoch)pracovných dní. Príkazca je povinný informovať bezodkladne, najneskôr do 5 (piatich) pracovných dní, Príkazníka a/alebo Advokáta o akýchkoľvek platbách jemu poskytnutých na vymáhanú Pohľadávku, vrátane akýchkoľvek (akéhokoľvek) zápočtov (započítania) na ňu.
            <br><br>5.2.	Príkazca zodpovedá za skutočnosť, že všetky Príkazníkovi a/alebo Advokátovi poskytnuté informácie sú pravdivé a úplné, že Pohľadávka existuje, a nesie plnú právnu zodpovednosť za škodu spôsobenú týmto nepravdivým uistením Príkazníka a/alebo Advokáta.
            <br><br>5.3.	Príkazca je povinný súčasne s podpisom Príkaznej zmluvy vystaviť Advokátovi písomnú plnú moc oprávňujúcu ho ku konaniam, ktoré sú predmetomPríkaznej zmluvy. Advokát Príkazcovi nezaručuje konečný výsledok v právnej veci, v ktorej mu poskytuje právne služby.
            <br><br>5.4.	Zmluvné strany sa dohodli, že súdne poplatky a preddavky na vykonanie dôkazov (na znalecký posudok apod.), prípadne náklady súdne nariadenej mediácie, vzniknuté v súvislosti s vymáhaním Pohľadávky, hradí Príkazca. Príkazca berie na vedomie, že v prípade neuhradenia preddavkov na vykonanie dôkazov môže dôjsť k nevykonaniu navrhnutého dôkazu ako aj k prípadnému zamietnutiu žaloby, a k uloženiu povinnosti Príkazcovi uhradiť žalovanému náhradu trov konania.
            <br><br>5.5.	Príkazca sa zaväzuje neuzavrieť po dobu trvania Príkaznej zmluvy s akoukoľvek treťou osobou Príkaznú zmluvu či obdobnú zmluvu, ktorej predmetom by bolo zariadenia či uskutočnenie záležitosti či jej časti, ako vyplýva z Príkaznej zmluvy.
        </p>
        <br>
        <h2>6. POVINNOSŤ MLČANLIVOSTI</h2>
        <p>6.1.	Príkazník sa zaväzuje zachovávať mlčanlivosť o skutočnostiach, o ktorých sa dozvedel v súvislosti s poskytovaním služieb podľa Príkaznej zmluvy, ktoré nemožno v záujme Príkazcu oznamovať tretím osobám.
            <br><br>6.2.	Advokát sa zaväzuje zachovávať mlčanlivosť o všetkých skutočnostiach, o ktorých sa dozvedel v súvislosti s poskytovaním právnych služieb v zmysle Príkaznej zmluvy.
            <br><br>6.3.	Povinnosť zachovať mlčanlivosť sa nevzťahuje na prípady, keď ide o zákonom uloženú povinnosť prekaziť spáchanie trestného činu, prípadne iné povinnosti uložené iným právnym predpisom Slovenskej republiky alebo ak osobitný predpis na úseku predchádzania a odhaľovania legalizácie príjmov z trestnej činnosti a financovania terorizmuneustanovuje inak.
        </p>
        <br>
        <h2>7. TRVANIE PRÍKAZNEJ ZMLUVY</h2>
        <p>7.1.	Príkazná zmluva zaniká splnením záväzku dlžníka Príkazcu, ak je Pohľadávka vymožená, a ak je Príkazníkovi a/alebo Advokátovi uhradená jeho odmena podľa Príkaznej zmluvy, ak sa nedohodnú zmluvné strany inak.
            <br><br>7.2.	Príkazca je oprávnený Príkaznú zmluvu vypovedať aj bez uvedenia dôvodu, a to písomnou výpoveďou s jednomesačnou výpovednou lehotou, ktorá začína plynúť prvým dňom mesiaca nasledujúceho po mesiaci, v ktorom bola výpoveď doručená druhej zmluvnej strane.
            <br><br>7.3.	Príkazník je oprávnený Príkaznú zmluvu vypovedať z dôvodov porušenia povinností Príkazcu uvedených v článku 6 VOP, ak nie je porušenie na výzvu Príkazníka Príkazcom napravené, a to písomnou výpoveďou účinnou dňom doručenia výpovede Príkazcovi.
            <br><br>7.4.	Advokát je oprávnený Príkaznú zmluvu vypovedať aj bez uvedenia dôvodu, a to písomnou výpoveďou s jednomesačnou výpovednou lehotou, ktorá začína plynúť prvým dňom mesiaca nasledujúceho po mesiaci, v ktorom bola výpoveď doručená druhej zmluvnej strane.
            <br><br>7.5.	Advokát je oprávnený odstúpiť od Príkaznej zmluvy v prípadoch ustanovených zákonom č. 586/2003 Z. z. o advokácii v znení neskorších predpisov.
        </p>
        <br>
        <h2>8. DORUČOVANIE PÍSOMNOSTÍ</h2>
        <p>8.1.	Zmluvné strany sa dohodli, že všetky písomnosti, ktoré má doručiť/bude doručovať v zmysle Príkaznej zmluvy, ako aj po skončení Príkaznej zmluvy jedna zmluvná strana druhej zmluvnej strane, budú doručované prostredníctvom e-mailovej adresy (v prípade Príkazcu prostredníctvom e-mailovej adresy zadanej Príkazcom v zákazníckom účte Príkazcu; v prípade Príkazníka prostredníctvom e-mailovej adresy zverejnenej na webovej stránke www.vymozete.sk ) alebo prostredníctvom pošty doporučene na adresu druhej zmluvnej strany uvedenú v záhlaví Príkaznej zmluvy.
            <br><br>8.2.	E-mail sa považuje za doručený 3. dňom odo dňa jeho odoslania aj v prípade, ak sa o tom adresát nedozvie. Odoslanie e-mailu musí zmluvná strana, ktorá tvrdí, že e-mail odoslala hodnoverne preukázať.
            <br><br>8.3.	Písomnosť - zásielkadoručovaná prostredníctvom pošty sa považuje za doručenú dňom jej prevzatia adresátom – zmluvnou stranou, dňom, kedy zmluvná strana odmietne poštou doručovanú zásielku prevziať, alebo dňom, kedy pošta vráti doručovanú zásielku odosielajúcej zmluvnej strane ako nevyžiadaná v odbernej (úložnej) lehote alebo s oznámením adresát neznámy, prípadne ako zásielku nedoručenú.
        </p>
        <br>
        <h2>9. RIEŠENIE SPOROV</h2>
        <p>9.1.	Spory a/alebo nezrovnalosti medzi zmluvnými stranami, ktoré vzniknú na základe Príkaznej zmluvy alebo v akejkoľvek súvislosti s Príkaznou zmluvou sa budú  riešiť v prvom rade mimosúdnou cestou, a to vzájomnými rokovaniami zmluvných strán vedenými v dobrej viere. Ak sa tieto spory a/alebo nezrovnalosti nepodarí vyriešiť ani po takýchto vzájomných rokovaniach zmluvných strán, je ktorákoľvek zmluvná strana oprávnená predložiť tieto spory a/alebo nezrovnalosti medzi zmluvnými stranami, ktoré vzniknú na základe Príkaznej zmluvy alebo v akejkoľvek súvislosti s Príkaznou zmluvou na rozhodnutie vecne a miestne príslušnému  súdu Slovenskej republiky.
        </p>
        <br>
        <h2>10. OCHRANA OSOBNÝCH ÚDAJOV</h2>
        <p>10.1.	Príkazca ako dotknutá osoba registráciou v systéme Príkazníka a/alebo Advokáta a/alebo podpisom Príkaznej zmluve slobodne, výslovne a zrozumiteľne vyjadruje a dáva svoj písomný súhlas Príkazníkovi a Advokátovi na spracovanie svojich osobných údajov v zmysle Nariadenia Európskeho parlamentu a Rady (EÚ) 2016/679 z 27.04.2016 o ochrane fyzických osôb pri spracúvaní osobných údajov a o voľnom pohybe takýchto údajov, ktorým sa zrušuje smernica 95/46/ES (všeobecné nariadenie o ochrane údajov) (ďalej len „Nariadenie GDPR“) a v zmysle zákona č. 18/2018 Z. z. o ochrane osobných údajov a o zmene a doplnení niektorých zákonov a tým aj na získavanie osobných údajov nevyhnutných na dosiahnutie účelu spracúvania (t.j. na plnenie Príkaznej zmluvy) ich kopírovaním, skenovaním alebo iným zaznamenávaním úradných dokladov na nosič informácií a na poskytnutie osobných údajov z informačného systému inej právnickej osobe, fyzickej osobe, prípadne subjektu v cudzine, ak zákon takýto súhlas vyžaduje (ďalej len „súhlas dotknutej osoby“). Súhlas dotknutej osoby je udelený na dobu trvania Príkaznej zmluvy. Dotknutá osoba je oprávnená kedykoľvek odvolať udelený súhlas. Aj po odvolaní súhlasu alebo uplynutí doby, na ktorý bol súhlas udelený, je však Príkazník a/alebo Advokát oprávnený spracovávať osobné údaje v rozsahu a počas obdobia vyžadovaného právnymi predpismi.
            <br><br>10.2.	Príkazník a Advokát spracováva všetky osobné údaje sám a vlastnými prostriedkami. Spracovaním osobných údajov nebol poverený žiaden sprostredkovateľ.
            <br><br>10.3.	Príkazca má ako dotknutá osoba všetky práva priznané Nariadením GDPR a zákonom č. 18/2018 Z.z. o ochrane osobných údajov a o zmene a doplnení niektorých zákonov a ďalšími právnymi predpismi.
            <br><br>10.4.	Príkazca ako dotknutá osoba vyhlasuje, že je vedomý si svojich práv v zmysle Nariadenia GDPR a zákona č. 18/2018 Z. z. o ochrane osobných údajov a o zmene a doplnení niektorých zákonov, a že mu boli poskytnuté zo strany Príkazníka a Advokáta všetky informácie podľa článku 13 a nasl. Nariadenia GDPR a  § 19 a nasl.Zákona č. 18/2018 Z. z. o ochrane osobných údajov.
            <br><br>10.5.	Príkazca vyhlasuje, že poskytnuté osobné údaje sú pravdivé a boli poskytnuté slobodne.
        </p>
        <br>
        <h2>11. OSTATNÉ USTANOVENIA</h2>
        <p>11.1.	Príkazník a Advokát sú oprávnení tieto VOP jednostranne meniť. Zmena a/alebo doplnenie VOP sa uskutoční vydaním nových VOP, účinnosťou ktorých zaniká účinnosť predchádzajúcich VOP. Zmenu VOP je Príkazník povinný uverejniť na svojej internetovej stránke a zaslať e-mailom Príkazcovi, a to najmenej 30 kalendárnych dní pred dňom nadobudnutia účinnosti nových VOP.
            <br><br>11.2.	V prípade, ak Príkazca v lehote najneskôr do dňa nadobudnutia účinnosti nových VOP neoznámi Príkazníkovi, že s novými VOP nesúhlasí, platí, že Príkazca sa s novými VOP oboznámil. S týmito súhlasí a tieto VOP sa stávajú dňom ich účinnosti pre zmluvné strany záväznými.
            <br><br>11.3.	V prípade, ak Príkazca oznámi Príkazníkovi, že s novými VOP nesúhlasí, v takomto prípade dňom účinnosti nových VOP, zmluva zaniká.
            <br><br>11.4.	V prípade,  ak by bolo alebo sa stalo niektoré z ustanovení VOP neplatným, neúčinným alebo nevymožiteľným nebude tým dotknutá ani obmedzená platnosť, účinnosť a vykonateľnosť ostatných ustanovení týchto VOP. Ak nastane takáto situácia, zmluvné strany nahradia takéto neplatné, neúčinné či nevymáhateľné ustanovenie iným ustanovením, ktoré najlepšie zodpovedá rovnakým obchodným účelom ako ustanovenie neplatné, neúčinné alebo nevymáhateľné alebo sa dohodnú na riešení, ktoré zachová kontext a účel daného ustanovenia.
        </p>
        <br>
        <h2>12. ZÁVEREČNÉ USTANOVENIA</h2>
        <p>12.1.	Tieto VOP sú neoddeliteľnou súčasťou Príkaznej zmluvy uzatvorenej medzi Príkazníkom, Advokátom a Príkazcom.
            <br><br>12.2.	Tieto VOP ako aj všetky právne vzťahy s nimi súvisiace sa riadia právnymi predpismi Slovenskej republiky.
            <br><br>12.3.	Tieto VOP nadobúdajú platnosť a účinnosť dňa 01.09.2018.
        </p>
    </article>
</div>
@endsection
