<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Admin routes */
Route::namespace('Admin')->prefix('admin')->name('admin.')
//    ->middleware('authAdmin')
    ->group(function() {
        Route::get('/', 'HomeController@index')->name('home')->middleware('auth:admin');
        Route::get('/login', 'LoginController@showLoginForm')->name('loginForm')->middleware('guest:admin');
        Route::post('/login', 'LoginController@login')->name('login')->middleware('guest:admin');
        Route::get('/logout', 'LoginController@logout')->name('logout');
        Route::get('/password/reset', 'LoginController@passwordReset')->name('password.reset');

});


/* Front routes */
Route::namespace('Front')->name('front.')->middleware('auth:web')->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::get('/', 'PublicController@index');
Route::get('/vop', 'PublicController@vop');
/* Auth routes generated by Laravel */
Auth::routes();
//hack to allow GET method for Laravel logout route
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
